export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';
export const TITLE_CHANGED = 'TITLE_CHANGED';

export const NOTE_ADD = 'NOTE_ADD';
export const NOTE_EDIT  = 'NOTE_EDIT';
export const NOTE_ARCHIVE = 'NOTE_ARCHIVE';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
